# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(550, 500)
        Window.setMinimumSize(QtCore.QSize(550, 500))
        Window.setMaximumSize(QtCore.QSize(550, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../MAXEK/PNG для фотошоп/AESTHETIC PNG\'S PACK 2 BY ROCKIGWITHLIGHTS/rockingwithlights16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-20, -10, 651, 515))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.button = QtWidgets.QPushButton(self.frame)
        self.button.setGeometry(QtCore.QRect(180, 285, 231, 81))
        self.button.setMinimumSize(QtCore.QSize(0, 2))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        self.button.setFont(font)
        self.button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button.setObjectName("button")
        self.main_label = QtWidgets.QLabel(self.frame)
        self.main_label.setGeometry(QtCore.QRect(160, 130, 280, 40))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.main_label.setFont(font)
        self.main_label.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.main_label.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"\n"
"")
        self.main_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_label.setObjectName("main_label")
        self.label_result = QtWidgets.QLabel(self.frame)
        self.label_result.setGeometry(QtCore.QRect(195, 230, 200, 45))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"text-align:center;\n"
"")
        self.label_result.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_result.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_result.setText("")
        self.label_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 551, 501))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("2.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label.raise_()
        self.button.raise_()
        self.main_label.raise_()
        self.label_result.raise_()
        Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Рембаза Roulette"))
        self.button.setText(_translate("Window", "Узнать кто лох джимба!"))
        self.main_label.setText(_translate("Window", "Тот самый лох из РМБЗ_Гэнг:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QMainWindow()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())
